project_id = "tibawkrjihvibckxutvj"

[functions.analyze-policy]
verify_jwt = true

[functions.passkey-register]
verify_jwt = true

[functions.fetch-rss]
verify_jwt = true

[functions.passkey-authenticate]
verify_jwt = false

[functions.alpaca-test]
verify_jwt = true

[functions.fetch-fred-data]
verify_jwt = true

[functions.cleanup-trash]
verify_jwt = false

[functions.fetch-israel-cpi]
verify_jwt = true

[functions.gcal-auth]
verify_jwt = true

[functions.gcal-events]
verify_jwt = true

[functions.gcal-sync]
verify_jwt = true

[functions.gcal-calendars]
verify_jwt = true
